[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "0.16.1" }
serde = "1.0"

[features]
# For fast proving on MacOS
metal = ["risc0-zkvm/metal"]
